---
# tasks file for tc-rate
- block:
  - name: tc rate setting
    template:
      src: 99-tc-rate.j2
      dest: /etc/NetworkManager/dispatcher.d/99-tc-rate
      owner: root
      group: root
      mode: 0755
      backup: yes
    register: is_tc_rate_setting
    notify: NetworkManager restart

  always:
  - name: tc rate backup settings
    include: backup.yml
    with_flattened:
      - "{{ is_tc_rate_setting|default() }}"
    loop_control:
      loop_var: backup_item
